name: career_pulse
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  http_parser: ^4.0.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  mime: ^1.0.6
  file_picker: ^8.1.2
  dio: ^5.7.0
  path_provider: ^2.1.4
  flutter_swiper_null_safety: ^1.0.2
  carousel_slider: ^4.2.0
  flutter_lints: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
